version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - "443:443"
      - "4510-4520:4510-4520"
      - '4563-4565:4563-4565'
      - "4567-4615:4567-4615"
      - '8055:8080'
    environment:
      - SERVICES=s3, lambda, dynamodb,lambdaLayers, cloudformation
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_API_KEY=32aN6jtJ2a
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'