AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A Node.js web service deployed to AWS Lambda.
Parameters:
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for
      which resources are provisioned and deployed.
    Default: production
Resources:
  ApiGwAccountConfig:
    DependsOn:
    - ClickCollectWebsocket
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
        - ClickCollectWebsocketLoggingRole
        - Arn
  ClickCollectWebsocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ClickCollectWebsocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.message
      CredentialsArn:
        Fn::GetAtt:
        - ClickCollectWebsocketRole
        - Arn
  ClickCollectConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      RouteKey: $connect
      AuthorizationType: CUSTOM
      AuthorizerId:
        Ref: CognitoLambdaAuthorizer
      OperationName: ClickCollectConnectRoute
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: ClickCollectConnectInteg
  ClickCollectConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      Description: Integration for builtin $connect route
      IntegrationType: AWS
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketRouteConnect.Arn}/invocations
  ClickCollectDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      RouteKey: $disconnect
      OperationName: ClickCollectDisconnectRoute
      RouteResponseSelectionExpression: $default
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: ClickCollectDisconnectInteg
  ClickCollectDisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      Description: Integration for builtin $disconnect route
      IntegrationType: AWS
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketRouteDisconnect.Arn}/invocations
  ClickCollectDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      RouteKey: $default
      OperationName: ClickCollectDefaultRoute
      RouteResponseSelectionExpression: $default
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: ClickCollectDefaultInteg
  ClickCollectDefaultInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      Description: Integration for builtin $default route
      IntegrationType: MOCK
  ClickCollectUpdateLocationRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      RouteKey: updateLocation
      OperationName: ClickCollectUpdateLocationRoute
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: ClickCollectUpdateLocationInteg
  ClickCollectUpdateLocationInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      Description: Pairing request integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketRouteUpdateLocation.Arn}/invocations
  ClickCollectAcceptRequestRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      RouteKey: acceptRequest
      OperationName: ClickCollectAcceptRequestRoute
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: ClickCollectAcceptRequestInteg
  ClickCollectAcceptRequestInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      Description: Integration for custom 'status' route
      IntegrationType: AWS
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketRouteAcceptRequest.Arn}/invocations
  ClickCollectRejectRequestRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      RouteKey: rejectRequest
      OperationName: ClickCollectRejectRequestRoute
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: ClickCollectRejectRequestInteg
  ClickCollectRejectRequestInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      Description: Integration for custom 'status' route
      IntegrationType: AWS
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketRouteRejectRequest.Arn}/invocations
  ClickCollectSubmitAnswersRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      RouteKey: submitAnswers
      OperationName: ClickCollectSubmitAnswersRoute
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: ClickCollectSubmitAnswersInteg
  ClickCollectSubmitAnswersInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
      Description: Integration for custom 'status' route
      IntegrationType: AWS
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketRouteSubmitAnswers.Arn}/invocations
  CognitoLambdaAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      Name: CustomCognitoAuthorizer
      ApiId:
        Ref: ClickCollectWebsocket
      AuthorizerType: REQUEST
      AuthorizerUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaCognitoAuthorizer.Arn}/invocations
      IdentitySource:
      - route.request.querystring.Authorizer
  ClickCollectWebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ClickCollectConnectRoute
    - ClickCollectDisconnectRoute
    - ClickCollectDefaultRoute
    - ClickCollectUpdateLocationRoute
    - ClickCollectAcceptRequestRoute
    Properties:
      ApiId:
        Ref: ClickCollectWebsocket
  ClickCollectWebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName:
        Fn::Sub: ${Stage}
      Description:
        Fn::Sub: ${Stage} traffic
      DeploymentId:
        Ref: ClickCollectWebSocketDeployment
      ApiId:
        Ref: ClickCollectWebsocket
      DefaultRouteSettings:
        LoggingLevel: INFO
        DataTraceEnabled: true
      AccessLogSettings:
        DestinationArn:
          Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:clickcollect-wss-access-logs
        Format: '''{"requestId":"$context.requestId", "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller", "user":"$context.identity.user","requestTime":"$context.requestTime",
          "eventType":"$context.eventType","routeKey":"$context.routeKey", "status":"$context.status","connectionId":"$context.connectionId"}'''
  PendingRequestsQue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 86400
      QueueName: PendingRequests
      VisibilityTimeout: 300
  PendingGamesQue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 86400
      QueueName: PendingGames
      VisibilityTimeout: 300
  WebSocketRouteConnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: webSocketRouteConnect
      Handler: connect.handler
      Runtime: nodejs12.x
      CodeUri: s3://ali-su-artifacts/1c774721bb4fb5be5cdba2dd547b0e5e
      Layers:
      - Ref: serverlessLayer
      Timeout: 3
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - MatchPlayersRole
        - Arn
      Environment:
        Variables:
          API_GATEWAY_REGION: us-east-1
          DYNAMODB_REQUESTS_TABLE: requests
  WebSocketRouteDisconnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: webSocketRouteDisconnect
      Handler: disconnect.handler
      Runtime: nodejs12.x
      CodeUri: s3://ali-su-artifacts/471579494eb5a6f79927bcb67f577c8d
      Layers:
      - Ref: serverlessLayer
      Timeout: 3
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - MatchPlayersRole
        - Arn
      Environment:
        Variables:
          API_GATEWAY_REGION: us-east-1
          DYNAMODB_REQUESTS_TABLE: requests
  WebSocketRouteUpdateLocation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: webSocketRouteUpdateLocation
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: s3://ali-su-artifacts/5123d7212c79c99e219018abbb40038b
      Layers:
      - Ref: serverlessLayer
      Timeout: 3
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - MatchPlayersRole
        - Arn
  WebSocketRouteAcceptRequest:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: webSocketRouteAcceptRequest
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: s3://ali-su-artifacts/35076e90dfea691bbc0c24d5a22d8f03
      Layers:
      - Ref: serverlessLayer
      Timeout: 3
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - MatchPlayersRole
        - Arn
  WebSocketRouteRejectRequest:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: webSocketRouteRejectRequest
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: s3://ali-su-artifacts/b6b15e169894e24da1e8572ccf26e276
      Layers:
      - Ref: serverlessLayer
      Timeout: 3
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - MatchPlayersRole
        - Arn
  WebSocketRouteSubmitAnswers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: webSocketRouteSubmitAnswers
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: s3://ali-su-artifacts/f4ba310017f10050f3449918887abc89
      Layers:
      - Ref: serverlessLayer
      Timeout: 3
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - MatchPlayersRole
        - Arn
  LambdaCognitoAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaCognitoAuthorizer
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: s3://ali-su-artifacts/c7d6894042cfbf03637626b6ca477ef5
      Layers:
      - Ref: serverlessLayer
      Timeout: 3
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - MatchPlayersRole
        - Arn
      Environment:
        Variables:
          COGNITO_USER_POOL: us-east-1_5i9hLQyTN
          COGNITO_USER_POOL_CLIENT: gdvig07kj34c7lttk57ccgebc
          KEYS_URL: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_5i9hLQyTN/.well-known/jwks.json
  matchPlayers:
    Type: AWS::Serverless::Function
    DependsOn:
    - FetchLambdaCodeFromS3
    Properties:
      FunctionName: matchPlayers
      Handler: matchPlayers.handler
      Runtime: nodejs12.x
      CodeUri: s3://ali-su-artifacts/c0cfe8fabc449784f8a52de07b114d3c
      Layers:
      - Ref: serverlessLayer
      Timeout: 3
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - MatchPlayersRole
        - Arn
      Environment:
        Variables:
          API_GATEWAY_REGION: us-east-1
          DYNAMODB_REQUESTS_TABLE: requests
          PLAYERS_DISTANCE: 100
          SQS_PENDINGREQUESTS_URL:
            Ref: PendingRequestsQue
          WEBSOCKET_API_ENDPOINT:
            Fn::Sub: https://${ClickCollectWebsocket}.execute-api.${AWS::Region}.amazonaws.com/${ClickCollectWebSocketStage}/@connections
  serverlessLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: serverlessLayer
      Description: Layer description
      ContentUri: s3://ali-su-artifacts/64ac710842dc1e8e9b26c35374849be9
      CompatibleRuntimes:
      - nodejs12.x
      - nodejs8.10
      LicenseInfo: Available under the MIT-0 license.
      RetentionPolicy: Retain
  ClickCollectConnectIntegPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: WebSocketRouteConnect
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ClickCollectWebsocket}/*/$connect
  ClickCollectDisconnectIntegPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: WebSocketRouteDisconnect
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ClickCollectWebsocket}/*/$disconnect
  ClickCollectUpdateLocationIntegPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: WebSocketRouteUpdateLocation
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ClickCollectWebsocket}/*/updateLocation
  ClickCollectAcceptRequestPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: WebSocketRouteAcceptRequest
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ClickCollectWebsocket}/*/acceptRequest
  ClickCollectRejectRequestIntegPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: WebSocketRouteRejectRequest
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ClickCollectWebsocket}/*/rejectRequest
  ClickCollectSubmitAnswersIntegPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: WebSocketRouteSubmitAnswers
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ClickCollectWebsocket}/*/submitAnswers
  LambdaCognitoAuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: LambdaCognitoAuthorizer
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ClickCollectWebsocket}/authorizers/${CognitoLambdaAuthorizer}
  MatchPlayersRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: LambdaBasicExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
      Path: /
  ClickCollectWebsocketRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: LambdaBasicExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
      Path: /
  ClickCollectWebsocketLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  FetchLambdaCodeFromS3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: FetchLambdaCodeFromS3
      Roles:
      - Ref: MatchPlayersRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:GetObjectACL
          Resource: arn:aws:s3:::ali-serverless-architecture/*
