'use strict';
if(process.env['DEV']) {
    require('dotenv').config()
}


const CONSTANTS = {
    RSTUDIO_INSTANCE: process.env.RSTUDIO_INSTANCE,
    ENVIRONMENT: process.env.ENVIRONMENT,
    COGNITO_USER_POOL: process.env.COGNITO_USER_POOL,
    COGNITO_USER_POOL_CLIENT: process.env.COGNITO_USER_POOL_CLIENT,
    CORS_ORIGIN: process.env.CORS_ORIGIN,
    BUCKET_NAME: process.env.BUCKET_NAME,
    DYNAMODB_FILES_GSI: process.env.DYNAMODB_FILES_GSI,
    DYNAMODB_FILES_TABLE: process.env.DYNAMODB_FILES_TABLE,
    DYNAMODB_JOBS_STATE_GSI: process.env.DYNAMODB_JOBS_STATE_GSI,
    DYNAMODB_JOBS_TIME_GSI: process.env.DYNAMODB_JOBS_TIME_GSI,
    DYNAMODB_JOBS_TABLE: process.env.DYNAMODB_JOBS_TABLE,
    DYNAMODB_SOCKETS_TYPE_GSI: process.env.DYNAMODB_SOCKETS_TYPE_GSI,
    DYNAMODB_REQUESTS_TABLE: process.env.DYNAMODB_REQUESTS_TABLE,
    DYNAMODB_REQUESTS_TABLE_REGION: process.env.DYNAMODB_REQUESTS_TABLE_REGION,
    DYNAMODB_GAMES_TABLE: process.env.DYNAMODB_GAMES_TABLE,
    DYNAMODB_GAMES_TABLE_REGION: process.env.DYNAMODB_GAMES_TABLE_REGION,
    DYNAMODB_QUESTIONS_TABLE: process.env.DYNAMODB_QUESTIONS_TABLE,
    DYNAMODB_QUESTIONS_TABLE_REGION: process.env.DYNAMODB_QUESTIONS_TABLE_REGION,
    DYNAMODB_OPTIONS: {},
    GLUE_JOB_NAME: process.env.GLUE_JOB_NAME,
    KEYS_URL: process.env.KEYS_URL,
    SIGNED_URL_EXPIRE_SECONDS: 60 * 60,
    WEBSOCKET_API_ENDPOINT: process.env.WEBSOCKET_API_ENDPOINT,
    API_GATEWAY_REGION: process.env.API_GATEWAY_REGION,
    MONGO_DB_URI: process.env.MONGO_DB_URI,
    SQS_PENDINGREQUESTS_URL: process.env.SQS_PENDINGREQUESTS_URL,
    SQS_SCHEDULE_NEXT_QUESTION_URL: process.env.SQS_SCHEDULE_NEXT_QUESTION_URL,
    PLAYERS_DISTANCE: process.env.PLAYERS_DISTANCE
};

module.exports = CONSTANTS;